### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by jethrogb** [jethrogb/rust-cexpr#23]
I'm currently reviewing PRs on a best-effort basis, which may take a month or so. If someone is willing to co-maintain this, that'd be great.

**Comment by jrmuizel** [comment]
I'd be willing to co-maintain. We depend on this transitively through `https://github.com/rust-lang/rust-bindgen` so I don't want to see it abandoned.

**Comment by emilio** [comment]
I'm happy to help out too, for the same reason. Not sure I can do active development, but I should've time for reviews and so on :)

**Comment by nox** [comment]
@jethrogb Do you still need comaintainers?

**Comment by jethrogb** [comment]
Both @jrmuizel and @emilio were added as co-maintainers
